// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_wMgBoFkQKTHsjnt8NXX0rCsuYalDaU8',
    appId: '1:1033275894064:android:7db5925e1b6176022840f5',
    messagingSenderId: '1033275894064',
    projectId: 'final-project-2a0d9',
    storageBucket: 'final-project-2a0d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJtU04GpufO0n598Es_SwyLYRkRW3GEg',
    appId: '1:1033275894064:ios:31f140af54cfe1152840f5',
    messagingSenderId: '1033275894064',
    projectId: 'final-project-2a0d9',
    storageBucket: 'final-project-2a0d9.appspot.com',
    androidClientId: '1033275894064-06tjoem3orc2kcq4gplvtr11ntu2v5q7.apps.googleusercontent.com',
    iosClientId: '1033275894064-fe2p1o43cqvnjdeels5f6699b2d3f17j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

}